name: marina_gandiense_app_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_route: ^5.0.0 # paquete de navegación para simplificar su configuracion con codigo autogenerado https://pub.dev/packages/auto_route
  bloc: ^8.0.3 # libreria de manejo de estado  (paquete base) https://pub.dev/packages/bloc
  flutter_bloc: ^8.1.1 # libreria de manejo de estado https://pub.dev/packages/flutter_bloc
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1 #libreria para programción funcional, para usar el objeto Either<R,L> y poder devolver dos objetos en las asincronas https://pub.dev/packages/dartz
  dio: ^4.0.6 #libreria http https://pub.dev/packages/dio
  equatable: ^2.0.5 # libreria que sobrescribe el operador == para poder comparar de forma facil dos objetos
  flutter:
    sdk: flutter   
  freezed: ^2.1.0+1 # paquete que genera codigo en los objetos y las omite para no tener clases largisimas https://pub.dev/packages/freezed
  freezed_annotation: ^2.1.0 # https://pub.dev/packages/freezed_annotation
  get_it: ^7.2.0 #Injeccion de dependencias https://pub.dev/packages/get_it
  json_annotation: ^4.6.0 # Serializar y deserializar json https://pub.dev/packages/json_annotation
  shared_preferences: ^2.0.15 # https://pub.dev/packages/shared_preferences

dev_dependencies:
  auto_route_generator: ^5.0.0
  #build_runner: ^2.2.0 me pide que active el ejecutar codigod e terceros en windows
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
